stages:
  - build
  - test
  - deploy

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t my-microservice .

test:
  stage: test
  script:
    - docker run --rm my-microservice npm test  # Add tests in package.json

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    # Here, add your deployment steps (push to a server)
