version: '3.8'

services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "4001:4001"
    # environment:
    #   - DB_URI=mongodb://mongo:27017/products  # Change here
    env_file:
      - .env.${ENV}
    depends_on:
      mongo:
        condition: service_healthy

  order-service:
    build:
      context: ./order-service
    ports:
      - "4002:4002"
    env_file:
      - .env.${ENV}
    # environment:
    #   - DB_URI=mongodb://mongo:27017/orders  # Change here
    #   - PRODUCT_SERVICE_URL=http://product-service:4001/api/products
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Persist data
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]  # Health check command
      interval: 30s  # Check every 30 seconds
      timeout: 10s   # Timeout after 10 seconds
      retries: 5     # Retry 5 times before considering the service unhealthy

  nginx:
    image: nginx:alpine
    ports:
      - "8002:8002"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product-service
      - order-service
volumes:
  mongo_data:  # Define the volume